- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      community.general.pacman:
        update_cache: yes
      changed_when: False

  tasks:
    - include_tasks: tasks/packages.yml
