- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      community.general.pacman:
        update_cache: yes
      changed_when: False

    - name: update whole system
      community.general.pacman:
        upgrade: yes

  tasks:
    - include_tasks: tasks/packages.yml
